// Comprehensive dictionary mapping ICAO designators to full airline names
const AIRLINE_ICAO_MAP: Record<string, string> = {
  AAL: "American Airlines",
  AAR: "Asiana Airlines",
  AAY: "Allegiant Air",
  ABW: "AirBridgeCargo",
  ABX: "ABX Air",
  ACA: "Air Canada",
  ACI: "Aircalin",
  AEA: "Air Europa",
  AEG: "Brussels Airlines",
  AFL: "Aeroflot",
  AFR: "Air France",
  AHY: "Azerbaijan Airlines",
  AIC: "Air India",
  AIZ: "Arkia Israel Airlines",
  AJT: "Amerijet International",
  AKL: "Air Kiribati",
  ALK: "SriLankan Airlines",
  AMX: "Aeromexico",
  ANA: "All Nippon Airways",
  ANS: "Andes Líneas Aéreas",
  ANZ: "Air New Zealand",
  ARG: "Aerolineas Argentinas",
  ASA: "Alaska Airlines",
  ASL: "Air Serbia",
  ASV: "Air Seoul",
  AVA: "Avianca",
  AVN: "Air Vanuatu",
  AXM: "AirAsia",
  AYY: "Aurigny Air Services",
  AZA: "Alitalia / ITA Airways",
  AZG: "Silk Way West Airlines",
  AZU: "Azul Brazilian Airlines",
  BAW: "British Airways",
  BBR: "Binter Canarias",
  BCS: "European Air Transport (DHL)",
  BEL: "Brussels Airlines",
  BER: "airberlin",
  BGH: "BH Air",
  BKP: "Bangkok Airways",
  BLR: "Atlantic Airways",
  BMI: "british midland",
  BMS: "Blue Air",
  BOE: "Boeing Flight Test",
  BOX: "AeroLogic",
  BPA: "Blue Panorama Airlines",
  BQA: "Bahamasair",
  BRA: "Braathens Regional Airlines",
  BRU: "Belavia",
  BTI: "airBaltic",
  BUC: "European Air Charter",
  CAL: "China Airlines",
  CAV: "Calm Air",
  CCA: "Air China",
  CDG: "Corsair International",
  CEB: "Cebu Pacific",
  CES: "China Eastern Airlines",
  CHD: "Hainan Airlines",
  CHH: "Hainan Airlines",
  CHP: "Copa Airlines",
  CIM: "Cimber Air",
  CKS: "Kalitta Air",
  CLH: "Lufthansa CityLine",
  CLX: "Cargolux",
  CMP: "Copa Airlines",
  CNA: "China Northern Airlines",
  CND: "Corendon Dutch Airlines",
  COA: "Continental Airlines",
  CPA: "Cathay Pacific",
  CQN: "Chongqing Airlines",
  CRL: "Corsairfly",
  CSN: "China Southern Airlines",
  CTN: "Croatia Airlines",
  CUB: "Cubana de Aviación",
  CXA: "XiamenAir",
  CYP: "Cyprus Airways",
  DAH: "Air Algérie",
  DAL: "Delta Air Lines",
  DAN: "Dan-Air",
  DFR: "Danish Air Transport",
  DLA: "Dolomiti",
  DLH: "Lufthansa",
  DTR: "DAT Danish Air Transport",
  EAL: "Eastern Air Lines",
  EIN: "Aer Lingus",
  ELG: "Alisarda",
  ELY: "El Al",
  ENT: "Enter Air",
  ETD: "Etihad Airways",
  ETH: "Ethiopian Airlines",
  EVE: "Evelop Airlines",
  EVA: "EVA Air",
  EWG: "Eurowings",
  EWR: "Eurowings Europe",
  EXS: "Jet2.com",
  EXY: "EasyJet",
  EZY: "EasyJet",
  EZS: "EasyJet Switzerland",
  FDX: "FedEx Express",
  FIN: "Finnair",
  FJI: "Fiji Airways",
  FLG: "Endeavor Air",
  FLI: "Atlantic Airways",
  FPO: "ASL Airlines France",
  FTU: "Flight Calibration Services",
  GAF: "German Air Force",
  GEC: "Lufthansa Cargo",
  GFA: "Gulf Air",
  GHA: "Ghana Airways",
  GIA: "Garuda Indonesia",
  GLO: "Gol Transportes Aéreos",
  GMI: "Germania",
  GTI: "Atlas Air",
  GTR: "SkyWest Airlines",
  HAL: "Hawaiian Airlines",
  HDA: "Cathay Dragon",
  HFF: "Huns Air",
  HLF: "Hapag-Lloyd",
  HLN: "Heavylift Cargo Airlines",
  HMY: "HMY Airways",
  HVN: "Vietnam Airlines",
  IBE: "Iberia",
  IBS: "Iberia Express",
  ICE: "Icelandair",
  IDA: "Idaho Air National Guard",
  IRA: "Iran Air",
  IRC: "Iran Aseman Airlines",
  ISG: "ITA Airways",
  ITY: "ITA Airways",
  IWD: "Iberojet",
  IYE: "Yemenia",
  JAF: "TUI fly Belgium",
  JAL: "Japan Airlines",
  JAV: "Jordan Aviation",
  JAZ: "JALways",
  JBU: "JetBlue Airways",
  JCO: "Cobham Aviation Services",
  JSA: "Jetstar Asia Airways",
  JST: "Jetstar Airways",
  JXX: "JetX",
  KAC: "Kuwait Airways",
  KAL: "Korean Air",
  KAP: "Cape Air",
  KFA: "Kenya Airways",
  KHV: "Khabarovsk Airlines",
  KLM: "KLM Royal Dutch Airlines",
  KNE: "Flynas",
  KQA: "Kenya Airways",
  KZR: "Air Astana",
  LAA: "Libyan Airlines",
  LAN: "LATAM Airlines",
  LBC: "Albanian Airlines",
  LCO: "LAN Cargo",
  LDG: "Luxair",
  LGL: "Luxair",
  LHN: "ExpressJet Airlines",
  LIA: "LIAT",
  LIL: "Air Liberté",
  LIT: "Air Lithuania",
  LIZ: "Air Horizon",
  LLR: "Alliance Air",
  LMG: "Laminair",
  LOF: "Trans States Airlines",
  LOG: "Loganair",
  LOT: "LOT Polish Airlines",
  LPA: "LATAM Paraguay",
  LTE: "LTE International Airways",
  LTU: "LTU International",
  LVR: "Aviaenergo",
  LXA: "Luxaviation",
  LZB: "Bulgaria Air",
  MAA: "MasAir",
  MAC: "Macedonian Airlines",
  MAH: "Malev Hungarian Airlines",
  MAK: "Macedonian Airlines",
  MAS: "Malaysia Airlines",
  MAU: "Air Mauritius",
  MBD: "Mamba Air",
  MDO: "Medavia",
  MEA: "Middle East Airlines",
  MEP: "Midwest Airlines",
  MES: "Mesaba Airlines",
  MGL: "MIAT Mongolian Airlines",
  MKA: "MK Airlines",
  MLA: "Maldivian",
  MMD: "Alsie Express",
  MPH: "Martinair",
  MSR: "EgyptAir",
  MTN: "Mountain Air Cargo",
  MTR: "Metrojet",
  MXA: "Mexicana de Aviación",
  MYT: "MyTravel Airways",
  NCA: "Nippon Cargo Airlines",
  NJS: "National Jet Systems",
  NKS: "Spirit Airlines",
  NLG: "Nelair",
  NLY: "Niki",
  NMA: "Nesma Airlines",
  NOS: "Neos",
  NRA: "Nassau Air",
  NTR: "TNT Airways",
  OAL: "Olympic Air",
  OAS: "Oasis Hong Kong Airlines",
  OAW: "Helvetic Airways",
  OBS: "Orbest",
  OMA: "Oman Air",
  ONE: "Avianca Brasil",
  ORB: "Orenair",
  ORF: "Orenburg Airlines",
  PAG: "Pegasus Aviation",
  PAL: "Philippine Airlines",
  PAA: "Pan American World Airways",
  PBA: "Provincetown-Boston Airlines",
  PDA: "POD Aviation",
  PGA: "Portugália Airlines",
  PGT: "Pegasus Airlines",
  PIA: "Pakistan International Airlines",
  PLK: "Pulkovo Aviation Enterprise",
  PMT: "PMTair",
  PNX: "Phoenix Aviation",
  PRD: "Presidential Airways",
  QFA: "Qantas",
  QID: "QantasLink",
  QNK: "Qanot Sharq",
  QTR: "Qatar Airways",
  RAM: "Royal Air Maroc",
  RAV: "Ravsa",
  RBA: "Royal Brunei Airlines",
  REA: "Aer Arann",
  REP: "Republic Airlines",
  RFF: "Russian Federation Air Force",
  RJA: "Royal Jordanian",
  RKA: "RwandAir",
  RMY: "Régional",
  RNA: "Nepal Airlines",
  ROA: "Royal Air Force",
  ROM: "Royal Air Force of Oman",
  ROT: "TAROM",
  RPA: "Republic Airways",
  RRE: "Royal Express",
  RSC: "Republic Airlines",
  RWD: "RwandAir",
  RYR: "Ryanair",
  SAA: "South African Airways",
  SAM: "SAM Colombia",
  SAS: "Scandinavian Airlines",
  SAT: "SATA Air Açores",
  SAY: "Scot Airways",
  SBA: "SBA Airlines",
  SBI: "S7 Airlines",
  SBU: "Siberia Airlines",
  SCH: "Scilly Skybus",
  SDA: "Sudan Airways",
  SEY: "Air Seychelles",
  SGA: "Sichuan Airlines",
  SIA: "Singapore Airlines",
  SIB: "Siberia Airlines",
  SIC: "Sichuan Airlines",
  SKY: "Skymark Airlines",
  SLK: "SilkAir",
  SLM: "Surinam Airways",
  SNB: "Sterling Airlines",
  SNC: "Air Congo",
  SOO: "Southern Air",
  SPA: "Sierra Pacific Airlines",
  SQC: "Singapore Airlines Cargo",
  SUI: "Swissair",
  SVR: "Ural Airlines",
  SWA: "Southwest Airlines",
  SWD: "Southern Winds",
  SWR: "Swiss International Air Lines",
  SWT: "Swiftair",
  SWW: "Shandong Airlines",
  SYR: "Syrian Air",
  TAA: "TACA Airlines",
  TAB: "TAME",
  TAC: "TACA International Airlines",
  TAD: "TASS",
  TAE: "TACA Peru",
  TAM: "LATAM Brasil",
  TAP: "TAP Air Portugal",
  TAR: "Tunisair",
  TAY: "ASL Airlines Belgium",
  TCA: "Trans-Canada Air Lines",
  TCF: "Shuttle America",
  TCX: "Thomas Cook Airlines",
  TDR: "Trade Air",
  TFL: "TUI fly Netherlands",
  TGO: "Transportes Aéreos Guatemaltecos",
  TGW: "Scoot",
  THA: "Thai Airways",
  THY: "Turkish Airlines",
  THT: "Air Tahiti Nui",
  TMA: "Trans Mediterranean Airways",
  TMR: "TAM Montenegro",
  TMP: "Tampere Air",
  TOM: "TUI Airways (UK)",
  TPA: "Tampa Cargo",
  TPC: "Air Calédonie",
  TRA: "Transavia",
  TRK: "Tarhan Tower Airlines",
  TRS: "AirTran Airways",
  TSC: "Air Transat",
  TUA: "Turkmenistan Airlines",
  TUI: "TUI fly",
  TUM: "TUM AeroCarga",
  TUP: "Tupolev",
  TVF: "Transavia France",
  TWB: "T'way Air",
  TYR: "Tyrolean Airways",
  UAE: "Emirates",
  UAI: "Aero-Union",
  UAL: "United Airlines",
  UCA: "CommutAir",
  UDZ: "Utair",
  UKR: "Ukraine International Airlines",
  ULA: "Urga",
  UMA: "Urumqi Air",
  UNA: "Altyn Air",
  UPS: "UPS Airlines",
  UTA: "UTA French Airlines",
  UTT: "Utair Express",
  VAL: "Voyageur Airways",
  VAP: "Phuket Air",
  VAR: "Vanguard Airlines",
  VAU: "Volaris",
  VDA: "Volga-Dnepr Airlines",
  VEX: "Virgin Express",
  VHL: "Virgin Nigeria",
  VIB: "Volaris",
  VJC: "VietJet Air",
  VLG: "Vueling",
  VIR: "Virgin Atlantic",
  VLE: "Volare Airlines",
  VLM: "VLM Airlines",
  VLU: "ValuJet Airlines",
  VNL: "Vanilla Air",
  VOE: "Volotea",
  VOG: "Vologda Aviation Enterprise",
  VOZ: "Virgin Australia",
  VPA: "Vanguard Airlines",
  VRG: "VARIG",
  VSP: "Vasp",
  VTE: "Volare Web",
  VTG: "Vietnam Airlines",
  VTI: "ValuJet",
  VUK: "Volga-Dnepr",
  WAK: "Wings Air",
  WAL: "Western Airlines",
  WEN: "WestJet Encore",
  WFL: "World Focus",
  WIA: "Windward Islands Airways",
  WJA: "WestJet",
  WZZ: "Wizz Air",
  XAX: "AirAsia X",
  XLA: "Excel Airways",
  YZR: "Yangtze River Express",
  ZBA: "Zambia Airways",
  ZIP: "ZIPAIR Tokyo"
};

/**
 * Resolves an ICAO callsign to its commercial airline name or a general aviation classification.
 * @param callsign The flight callsign (e.g. "AIC102", "N395AM")
 * @returns The resolved airline/carrier name, or a fallback.
 */
export function getAirlineName(callsign: string): string {
  if (!callsign || callsign === "N/A" || callsign === "Unknown") {
    return "Unknown Carrier";
  }

  const clean = callsign.trim().toUpperCase();

  // 1. Extract 3-letter ICAO designator
  const icao3 = clean.substring(0, 3);
  if (AIRLINE_ICAO_MAP[icao3]) {
    return AIRLINE_ICAO_MAP[icao3];
  }

  // 2. Identify common General Aviation (GA) patterns
  // US Registry N-Numbers: 'N' followed by digits (e.g. N2349, N4952M)
  if (/^N[0-9]/.test(clean)) {
    return "General Aviation (US Registry)";
  }

  // UK Registry: 'G-' followed by 4 letters (e.g. G-ABCD)
  if (/^G-[A-Z]/.test(clean)) {
    return "General Aviation (UK Registry)";
  }

  // Canadian Registry: 'C-' followed by 4 letters
  if (/^C-[A-Z]/.test(clean)) {
    return "General Aviation (Canada Registry)";
  }

  // Australian Registry: 'VH-' followed by 3 letters
  if (/^VH-[A-Z]/.test(clean)) {
    return "General Aviation (Australia Registry)";
  }

  // German Registry: 'D-' followed by 4 digits or letters
  if (/^D-[A-Z0-9]/.test(clean)) {
    return "General Aviation (German Registry)";
  }

  // French Registry: 'F-' followed by 4 letters
  if (/^F-[A-Z]/.test(clean)) {
    return "General Aviation (French Registry)";
  }

  // Generic registry indicators (single letter prefixes followed by dash/numbers)
  if (/^[A-Z]-[A-Z0-9]/.test(clean)) {
    return "General/Private Aviation";
  }

  return "Unlisted Carrier";
}
